services:
  next-app:
    container_name: poke-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

    ports:
      - 3000:3000
