FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile

COPY src ./src
COPY public ./public
COPY tsconfig.json .
COPY next.config.mjs .

CMD ["pnpm", "dev"]